services:
  server_node:
    build:
      context: .
      dockerfile: server_node/Dockerfile
    container_name: server_node
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  server_python:
    build:
      context: .
      dockerfile: server_python/Dockerfile
    container_name: server_python
    ports:
      - 5001:5000

  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    container_name: front
    env_file:
      - front/.env
    ports:
      - 5173:5173
    depends_on:
      - server_node
      - server_python
